frontend/modules/user/models/UserSearch.php
<?php

namespace frontend\modules\user\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use vova07\users\models\frontend\User;

/**
 * UserSearch represents the model behind the search form about `vova07\users\models\frontend\User`.
 */
class UserSearch extends User
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'status_id'], 'integer'],
            [['phone', 'email', 'password_hash', 'auth_key', 'token', 'role', 'created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = User::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
            'status_id' => $this->status_id,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ]);

        $query->andFilterWhere(['like', 'phone', $this->phone])
            ->andFilterWhere(['like', 'email', $this->email])
            ->andFilterWhere(['like', 'password_hash', $this->password_hash])
            ->andFilterWhere(['like', 'auth_key', $this->auth_key])
            ->andFilterWhere(['like', 'token', $this->token])
            ->andFilterWhere(['like', 'role', $this->role]);

        return $dataProvider;
    }
}

frontend/modules/user/controllers/DefaultController.php
<?php

namespace frontend\modules\user\controllers;

use backend\modules\employment\models\PaidEmployment;
use backend\modules\pay\models\Pay;
use common\models\Profile;
use common\models\User;
use frontend\modules\user\User as Module;
use vova07\fileapi\actions\UploadAction as FileAPIUpload;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * DefaultController implements the CRUD actions for User model.
 */
class DefaultController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {

        $this->layout = '/cabinet';

        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'fileapi-upload' => [
                'class' => FileAPIUpload::className(),
                'path' => Profile::AVATAR_UPLOAD_TEMP_PATH,
            ]
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $paidEmployment = new ActiveDataProvider([
            'query' => PaidEmployment::find()
                ->select([
                    '{{%paid_employment}}.timetable_id',
                    '{{%paid_employment}}.date',
                    '{{%timetable}}.start',
                    '{{%timetable}}.end',
                    '{{%group}}.name',
                ])
                ->joinWith(['timetable.group', 'pay'])
                ->where(['{{%pay}}.user_id' => Yii::$app->user->id])
                ->andWhere('concat(`date`," ",`end`) >= NOW()')
                ->orderBy('`date`, `start`, `end`'),
            'pagination' => [
                'pageSize' => 30,
            ],
            'sort' => false,
        ]);

        return $this->render('index', [
            'dataProvider' => $paidEmployment,
        ]);
    }

    /**
     * Displays a single User model.
     * @return mixed
     */
    public function actionView()
    {
        $isActiveAffiliateProgram = Pay::isActiveAffiliateProgram();

        return $this->render('view', [
            'model' => $this->findModel(\Yii::$app->user->id),
            'isActiveAffiliateProgram' => $isActiveAffiliateProgram,
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Displays a single User model.
     * @return mixed
     */
    public function actionHistory()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Pay::find()->where(['user_id' => Yii::$app->user->id])
                ->orderBy(['create_at' => SORT_DESC])
            ,
            'sort' => false,
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);

        return $this->render('history', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @return mixed
     */
    public function actionViewPay($id)
    {
        $paidEmployment = new ActiveDataProvider([
            'query' => PaidEmployment::find()
                ->select([
                    '{{%paid_employment}}.timetable_id',
                    '{{%paid_employment}}.date',
                    '{{%timetable}}.start',
                    '{{%timetable}}.end',
                    '{{%group}}.name',
                ])
                ->joinWith('timetable.group')
                ->where(['pay_id' => $id])
                ->orderBy('date'),
            'pagination' => [
                'pageSize' => 30,
            ],
            'sort' => false,
        ]);

        $model = Pay::find()->where('id = :id AND user_id=' . Yii::$app->user->id, [':id' => $id])->one();

        return $this->render('view_pay', [
            'model' => $model,
            'paidEmployment' => $paidEmployment,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionUpdate()
    {
        $profile = Profile::findOne(['user_id' => Yii::$app->user->id]);
        $profile->setScenario('frontend-update-own');

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            return ActiveForm::validate($profile);
        }

        if ($profile->load(Yii::$app->request->post()) && $profile->save()) {
            Yii::$app->session->setFlash('success', Module::t('user-frontend', 'Data successfully changed'));

            return $this->refresh();
        }

        return $this->render('update', ['profile' => $profile]);
    }

}

frontend/modules/user/views/default/_form.php
<?php

use vova07\fileapi\Widget;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;
use frontend\modules\user\User;

/* @var $this yii\web\View */
/* @var $profile common\models\Profile */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php
    $form = ActiveForm::begin(
                    [
                        'id' => 'user-form', 
                    ]
    );
    ?>

    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($profile, 'surname') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($profile, 'name') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($profile, 'middle_name') ?>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-4">
            <?=
            $form->field($profile, 'birthday')->widget(DatePicker::className(), [
//            'options'       => ['value' => date('d.m.Y')],
                'id'            => 'birthday',
                'type'          => DatePicker::TYPE_INPUT,
                'language'      => 'ru',
                'pluginOptions' => [
                    'autoclose' => true,
                    'startView' => 'decade',
                    'format'    => 'yyyy-mm-dd'
                ]
                    ]
            );
            ?>
        </div>
        <div class="col-sm-4">
            <?php
            echo $form->field($profile, 'gender')->dropDownList(
                    $profile->getGenderArray(), ['prompt' => User::t('user-frontend', 'Choose a gender')]
            );
            ?>
        </div>

        <div class="col-sm-4">
            <?=
            $form->field($profile, 'avatar_url')->widget(Widget::className(), [
                    'settings'         => [
                        'url' => ['fileapi-upload']
                    ],
                    'crop'             => true,
                    'cropResizeWidth'  => 100,
                    'cropResizeHeight' => 100
                ]
            )
            ?>
        </div>


    </div>
    <div class="row">
        <div class="col-sm-12">
            <?=
            Html::submitButton(User::t('user-frontend', 'Update'), [
                'class' => 'btn btn-success btn-large'
                    ]
            )
            ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

</div>

frontend/modules/user/views/default/history.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use frontend\modules\user\User;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\user\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                 = User::t('user-frontend', 'Payment history');
$this->params['breadcrumbs'] = [
    [
        'label' => User::t('user-frontend', 'Personal Area'),
        'url'   => ['default/index'],
    ],
    $this->title
];
?>
<div class="user-index">

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns'      => [
            [
                'attribute' => 'create_at',
            ],
            [
                'attribute' => 'ticket_id',
                'value'     => function ($model) {
                    return $model->ticket->title;
                },
            ],
            'current_cost',
            'cash',
            'bonus_cash',
            [
                'header'   => User::t('user-frontend', 'Actions'),
                'class'   => 'yii\grid\ActionColumn',
                'buttons' => [
                    'view-pay' => function($url, $model, $key) {
                        return Html::a(
                            '<i class="glyphicon glyphicon-eye-open"></i>',
                            $url,
                            [
                                'title' => User::t('user-frontend', 'View details'),
                                'class' => 'btn btn-primary btn-xs'
                            ]
                        );
                    },
                        ],
                        'template'     => '{view-pay}'
                    ]
                ],
            ]);
            ?>

</div>

frontend/modules/user/views/default/index.php
<?php

use frontend\modules\user\User;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\user\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = User::t('user-frontend', 'Personal Area');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
    <h4 class="text-capitalize"><?= User::t('user-frontend', 'Hello, {name}', ['name' => Yii::$app->user->identity->profile->name]); ?></h4>
    <hr />
    <?php
    // Предлагаем заполнить профиль
    if(empty(Yii::$app->user->identity->profile->surname) || empty(Yii::$app->user->identity->profile->gender)): ?>
        <div class="bg-danger" style="padding: 10px;">
            <?=
            User::t('user-frontend', 'Your profile is not full. Please fill it up, follow the link: {link}',
                    [
                        'link' => Html::a(User::t('user-frontend', 'Update profile'), ['update'])
                    ]
                )
            ?>
        </div>
        <hr />
    <?php endif; ?>
    <h5><?= User::t('user-frontend', 'Balance paid employment: {count}', ['count' => $dataProvider->getTotalCount()]); ?> </h5>
    <?php
    if ($dataProvider->getTotalCount() > 0) {
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'columns'      => [
                [
                    'attribute' => 'date',
                    'value'     => function ($model) {
                        return Yii::$app->formatter->asTime(strtotime($model->date), 'php:d.m.Y')
                                . ' (' . Yii::$app->formatter->asTime(strtotime($model->date), 'php:l') . ')';
                    }
                ],
                'timetable.start',
                'timetable.end',
                'timetable.group.name',
            ],
        ]);
    }
    ?>

</div>

frontend/modules/user/views/default/update.php
<?php

use frontend\modules\user\User;

/* @var $this yii\web\View */
/* @var $user common\models\User */

$this->title = User::t('user-frontend', 'Update profile');
$this->params['breadcrumbs'][] = ['label' => User::t('user-frontend', 'Personal Area'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-update">

    <?= $this->render('_form', ['profile' => $profile]) ?>

</div>

frontend/modules/user/views/default/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\modules\user\User;


/* @var $this yii\web\View */
/* @var $model \common\models\User */
/* @var $isActiveAffiliateProgram backend\modules\pay\models\Pay::isActiveAffiliateProgram(); */

$this->title                   = User::t('user-frontend', 'Profile');
$this->params['breadcrumbs'][] = ['label' => User::t('user-frontend', 'Personal Area'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">


    <?=
    DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'profile.FullAvatarUrl:image:' . Yii::t('app', 'Avatar'),
            'id',
            'profile.surname',
            'profile.name',
            'profile.middle_name',
            'phone',
            'email:email',
            [
                'attribute' => 'profile.gender',
                'value' => $model->profile->genderArray[$model->profile->gender]
            ],
            'profile.birthday:date',
            'profile.balance',
            'profile.bonus_balance',
            'created_at:datetime',
            'updated_at:datetime',
            [
                'label'  => User::t('user-frontend', 'Referral link to the home page'),
                'format' => 'raw',
                'value'  => ($isActiveAffiliateProgram) ?
                        Html::input(
                                'text', 'ref-link', Yii::$app->request->getHostInfo() . '/?ref=' . $model->id, 
                            [
                                'class'    => 'form-control input-sm',
                                'readonly' => 'readonly',
                                'onclick' => 'this.select();',
                            ]
                        ) :
                    User::t('user-frontend', 'Link available')
            ],
        ],
    ])
    ?>

</div>

frontend/modules/user/views/default/view_pay.php
<?php

use yii\widgets\DetailView;
use yii\grid\GridView;

$this->title                   = 'Просмотр платежа';
$this->params['breadcrumbs'][] = ['label' => 'Личный кабинет', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">


    <?=
    DetailView::widget([
        'model'      => $model,
        'attributes' => [
//                        'id',
                    [
                        'attribute' => 'ticket_id',
                        'value'     => $model->getTicket()->one()->title,
                    ],
                    'current_cost',
                    'cash',
                    'bonus_cash',
                    'create_at'
                ],
    ])
    ?>
    <hr />
            <div class="box-header">
                <h4>Оплаченные занятия</h4>
            </div>
            <?=
            GridView::widget([
                'dataProvider' => $paidEmployment,
                'id'           => 'paid-employment',
                'columns'      => [
                    [
                        'attribute' => 'date',
                        'value'     => function ($model) {
                            return  Yii::$app->formatter->asTime(strtotime($model->date),'php:d.m.Y')
                                    . ' ('.Yii::$app->formatter->asTime(strtotime($model->date), 'php:l').')';
                        }
                    ],
                    'timetable.start',
                    'timetable.end',
                    'timetable.group.name'
                ],
            ]);
            ?>

</div>